name: Monthly Scrape and Build

on:
  schedule:
    - cron: '0 0 1 * *' # Tous les 1er du mois à minuit UTC
  workflow_dispatch: # Permet de lancer manuellement si besoin

jobs:
  scrape-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape data and build HTML
        run: python main.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/data docs/*.html
          git commit -m "Monthly data scrape and HTML rebuild [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git gh-pages